name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ugsel_test
          MYSQL_USER: user_ugsel
          MYSQL_PASSWORD: pwd_ugsel
        ports:
          - 3306:3306

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer PHP et Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql
          coverage: none

      - name: Installer les dépendances
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Run migrations
        run: |
          php bin/console doctrine:migrations:migrate --env=test --no-interaction

      - name: Load test fixtures
        run: |
          php bin/console doctrine:fixtures:load --env=test --no-interaction

      - name: Vérifier le linting
        run: composer lint

      - name: Lancer les tests
        run: vendor/bin/phpunit
